"""empty message

Revision ID: dac0f61c2c61
Revises: e035a26946e5
Create Date: 2021-11-19 11:42:37.439044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dac0f61c2c61'
down_revision = 'e035a26946e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incident', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photos_taken', sa.Boolean(), nullable=False, default=False))
        batch_op.add_column(sa.Column('photographer', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incident', schema=None) as batch_op:
        batch_op.drop_column('photographer')
        batch_op.drop_column('photos_taken')

    # ### end Alembic commands ###
