"""empty message

Revision ID: e035a26946e5
Revises: 
Create Date: 2021-11-15 13:07:41.749021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e035a26946e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('pos', sa.String(), nullable=True),
    sa.Column('seatbelt', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('plate', sa.String(length=10), nullable=False),
    sa.Column('num_occupants', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(length=25), nullable=False),
    sa.Column('model', sa.String(length=25), nullable=False),
    sa.Column('color', sa.String(length=25), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incident',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crash_sequence', sa.String(length=15), nullable=True),
    sa.Column('date', sa.String(length=15), nullable=False),
    sa.Column('time', sa.String(length=10), nullable=False),
    sa.Column('county', sa.String(length=25), nullable=True),
    sa.Column('location', sa.String(length=25), nullable=True),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('num_vehicles', sa.Integer(), nullable=False),
    sa.Column('num_pedestrians', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('officer', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['officer'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crash_sequence')
    )
    op.create_table('supervises',
    sa.Column('supervisor', sa.Integer(), nullable=True),
    sa.Column('supervisee', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['supervisee'], ['user.id'], ),
    sa.ForeignKeyConstraint(['supervisor'], ['user.id'], )
    )
    op.create_table('assisting',
    sa.Column('officer', sa.Integer(), nullable=True),
    sa.Column('incident', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['incident'], ['incident.id'], ),
    sa.ForeignKeyConstraint(['officer'], ['user.id'], )
    )
    op.create_table('associated_vehicle',
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('damage', sa.String(), nullable=True),
    sa.Column('skid_before', sa.Float(), nullable=True),
    sa.Column('skid_after', sa.Float(), nullable=True),
    sa.Column('airbag_front', sa.Boolean(), nullable=True),
    sa.Column('airbag_side', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('incident_id', 'vehicle_id')
    )
    op.create_table('object',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('object_type', sa.String(length=25), nullable=False),
    sa.Column('is_ref1', sa.Boolean(), nullable=False),
    sa.Column('is_ref2', sa.Boolean(), nullable=False),
    sa.Column('north_or_rp1', sa.Float(), nullable=True),
    sa.Column('south_or_rp2', sa.Float(), nullable=True),
    sa.Column('east', sa.Float(), nullable=True),
    sa.Column('west', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('object')
    op.drop_table('associated_vehicle')
    op.drop_table('assisting')
    op.drop_table('supervises')
    op.drop_table('incident')
    op.drop_table('vehicle')
    op.drop_table('user')
    op.drop_table('person')
    # ### end Alembic commands ###
